# in docker in docker it must be version 2.2
# version: '2.2'
# default version 
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_1
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rede_externa
    volumes:
      - redis_data:/data 

  internal_celery_worker_1:
    image: mediacutsstudio/celery_worker:latest
    build:
      context: ./internal-media-cuts-studio-server
      dockerfile: Dockerfile 
    container_name: internal_celery_worker_1
    volumes:
      - logger_data:/app/Studio/Logs
    restart: always
    working_dir: /app
    command: >
      watchmedo auto-restart --directory=/app --pattern="*.py" --recursive -- 
      celery -A celery_worker worker --loglevel=info --beat
    depends_on:
      - redis
    networks:
      - rede_externa
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0  
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, utility]


networks:
  rede_externa:
    external: true

volumes:
  logger_data:
  redis_data: